name: Traverse bags to find duplicates

on:
    workflow_dispatch:  
  
    schedule:
      - cron: '0 0 * * *'  # run every day at midnight

jobs:
    trigger-public-workflow:
        runs-on: ubuntu-latest

        permissions:
            contents: write  
            packages: write  

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Clone private data storage
          run: |
            git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.BAGS }}.git bags_repo

        - name: Clone private logs storage
          run: |
            git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.DATA_STORAGE }}.git data_storage_repo
        
        - name: Install Node.js dependencies 
          run: npm install axios csv-parser dotenv shopify-api-node fs
        
        - name: Update products
          run: node /home/runner/work/duplicate_checker/duplicate_checker/duplicate_finder.js
          env:
              SHOP: ${{ secrets.SHOP }}
              SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
              IN_FILE: 'bags_repo/clean_data/existing_skus.csv'
              OUT_FOLDER: 'data_storage_repo/bags/'
              
  